# The URL the site will be built for
base_url = "https://creberust.github.io/"

# The site title and description.
title = "Creberust Blog"
description = "Personal Blog made with love for Rustaceans"

# The default language; used in feeds.
default_language = "en"

# Set the theme
theme = "linkita"

# Author of the site
author = "creberust"

# Automatically generate a feed. (type: boolean;)
generate_feeds = true

# The filenames to use for the feeds. (type: array of strings;)
feed_filenames = ["rss.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Enable KaTeX math formula support globally.
# (type: boolean; default value: `false`;)
math = true

# Enable Mermaid support globally.
# (type: boolean; default value: `false`;)
mermaid = true

# Enable comments globally.
# (type: boolean; default value: `false`;)
comment = false

# Title separator.
# (type: string; default value: ` | `;)
title_separator = " | "

# The top menu. See `extra.menus`.
# (type: string; no default value;)
header_menu_name = "menu_name"

# (type: boolean; default value: false;)
disable_default_favicon = false

# (type: boolean; default value: false;)
disable_javascript = false

# (type: boolean; default value: false;)
use_cdn = false

# You can reorder the strings, remove them, or replace them.
#  For example, you can replace `site_title` with `home_button`.
#  (type: array of strings; default value: `["site_title", "theme_button", "search_button", "translations_button"]`;)
# header_buttons = []

# Valid values:
#  `date`, `date_on_page`, `date_on_paginator`,
#  `date_updated, `date_updated_on_page, `date_updated_on_paginator`,
#  `reading_time, `reading_time_on_page, `reading_time_on_paginator`,
#  `word_count`, `word_count_on_page`, `word_count_on_paginator`,
#  `authors`, `authors_on_page`, `authors_on_paginator`,
#  `tags`, `tags_on_page`, `tags_on_paginator`.
#  (type: array of strings; default value: `["date", "date_updated_on_page", "reading_time", "authors"]`;)
# page_info = []

[extra.style]
# The custom background color. (type: string;)
bg_color = "#f4f4f5"
# The custom background color in dark mode. (type: string;)
bg_dark_color = "#18181b"

# Enable header blur. (type: boolean;)
header_blur = false

# The custom header color, only available
#  when `header_blur` is false. (type: string;)
header_color = "#e4e4e7"
# The custom header color in dark mode, only available
#  when `header_blur` is false. (type: string;)
header_dark_color = "#27272a"

[extra.menus]
menu_name = [
    { url = "$BASE_URL/pages/archive/", name = "Archive" },
    { url = "$BASE_URL/categories", name = "Categories" },
    { url = "$BASE_URL/tags/", name = "Tags" },
    { url = "$BASE_URL/pages/about/", name = "About" },
]

[extra.footer]
# Replace with the correct year.
# (type: number; default value: current year;)
since = 2025

# Replace with the url of the license you want.
# (type: string; no default value; supports `$BASE_URL`;)
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

# Replace `Your Name` with your name and `CC BY-SA 4.0` with the name of the license you want
copyright = "&copy; $YEAR Benjamin \"creberust\" Peter &vert; [CC BY-SA 4.0]($LICENSE_URL)"

# (type: string; no default value; supports `$BASE_URL`;)
# privacy_policy_url = "$BASE_URL/privacy-policy/"

# (type: string; no default value; supports `$BASE_URL`;)
# terms_of_service_url = "$BASE_URL/terms-of-service/"

# (type: string; no default value; supports `$BASE_URL`;)
# search_page_url = "$BASE_URL/search/"

[extra.profiles]

[extra.profiles.creberust]
name = "Creberust"
bio = "Hello World!"
email = "bpeter@tuta.com"
social = [
    { name = "github", url = "https://github.com/creberust" },
    { name = "bluesky", url = "https://bsky.app/profile/bpeter98.bsky.social" },
]
